### ISSUE TITLE
Issue starting Race

### ISSUE THREAD

**Issue by Duderocktv** [Sna-aaa/qb-sna-races#1]
![image](https://user-images.githubusercontent.com/49062165/177221075-4ba68afc-c589-4a3f-9540-717f7bf7fea6.png)

Added myself as whitelisted Citizen ID
Did /race
These are my settings:
![image](https://user-images.githubusercontent.com/49062165/177221117-979a606f-bdfc-42dc-b14e-2223547059b8.png)

Click on CREATE and then I get this error above ^

Starting a race as a "testing" race works fine.

**Comment by Sna-aaa** [comment]
Thanks a lot for the report, i've corrected this in the last update :)
